@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1.2 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Wed Jan 31 10:16:24 +0100 2024
REM SW Build 2615518 on Fri Aug  9 15:55:25 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto b3cb5d2098154d8b9ba66b127d838a2d --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip -L xpm --snapshot gestionChrono_tb_behav xil_defaultlib.gestionChrono_tb -log elaborate.log"
call xelab  -wto b3cb5d2098154d8b9ba66b127d838a2d --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip -L xpm --snapshot gestionChrono_tb_behav xil_defaultlib.gestionChrono_tb -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
